MAKE     = make -r

default :
	$(MAKE) -C 1line
	$(MAKE) -C bball
	$(MAKE) -C bonno
	$(MAKE) -C calc
	$(MAKE) -C clock
	$(MAKE) -C color
	$(MAKE) -C csvv
	$(MAKE) -C cvtg
	$(MAKE) -C gview
	$(MAKE) -C invader
	$(MAKE) -C keyview
	$(MAKE) -C kuha
	$(MAKE) -C luckynum
	$(MAKE) -C menu
	$(MAKE) -C mmlplay
	$(MAKE) -C mtorz
	$(MAKE) -C noodle
	$(MAKE) -C osakcnt
	$(MAKE) -C stbeep
	$(MAKE) -C tview
	$(MAKE) -C type
	$(MAKE) -C walk
	$(MAKE) -C winhello

clean :
	$(MAKE) -C 1line     clean
	$(MAKE) -C bball     clean
	$(MAKE) -C bonno     clean
	$(MAKE) -C calc      clean
	$(MAKE) -C clock     clean
	$(MAKE) -C color     clean
	$(MAKE) -C csvv      clean
	$(MAKE) -C cvtg      clean
	$(MAKE) -C gview     clean
	$(MAKE) -C invader   clean
	$(MAKE) -C keyview   clean
	$(MAKE) -C kuha      clean
	$(MAKE) -C luckynum  clean
	$(MAKE) -C menu      clean
	$(MAKE) -C mmlplay   clean
	$(MAKE) -C mtorz     clean
	$(MAKE) -C noodle    clean
	$(MAKE) -C osakcnt   clean
	$(MAKE) -C stbeep    clean
	$(MAKE) -C tview     clean
	$(MAKE) -C type      clean
	$(MAKE) -C walk      clean
	$(MAKE) -C winhello  clean

cleanall :
	$(MAKE) -C 1line     cleanall
	$(MAKE) -C bball     cleanall
	$(MAKE) -C bonno     cleanall
	$(MAKE) -C calc      cleanall
	$(MAKE) -C clock     cleanall
	$(MAKE) -C color     cleanall
	$(MAKE) -C csvv      cleanall
	$(MAKE) -C cvtg      cleanall
	$(MAKE) -C gview     cleanall
	$(MAKE) -C invader   cleanall
	$(MAKE) -C keyview   cleanall
	$(MAKE) -C kuha      cleanall
	$(MAKE) -C luckynum  cleanall
	$(MAKE) -C menu      cleanall
	$(MAKE) -C mmlplay   cleanall
	$(MAKE) -C mtorz     cleanall
	$(MAKE) -C noodle    cleanall
	$(MAKE) -C osakcnt   cleanall
	$(MAKE) -C stbeep    cleanall
	$(MAKE) -C tview     cleanall
	$(MAKE) -C type      cleanall
	$(MAKE) -C walk      cleanall
	$(MAKE) -C winhello  cleanall
